#CPSC 362 PROJECT
DROP DATABASE IF EXISTS COURSECATALOG;
CREATE DATABASE COURSECATALOG;

USE COURSECATALOG;

CREATE TABLE IF NOT EXISTS COURSE(
COURSEID			INT NOT NULL AUTO_INCREMENT,
DEPTCODE			CHAR(4) NOT NULL,
COURSENUM			SMALLINT NOT NULL,
COURSELETTER		CHAR,
COURSENAME			VARCHAR(100) NOT NULL,
COURSEDESCRIPTION	VARCHAR(300),
CREDITS				TINYINT NOT NULL,
GRADCREDIT			BOOL,
MAJMINREQ			BOOL,
PRIMARY KEY (COURSEID)
#OLD PK IS DEPTCODE, COURSENUM, COURSELETTER
)ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS COURSEPREREQ(
COURSEID			INT NOT NULL,
COURSEDEPT			CHAR(4) NOT NULL,
COURSENUM			SMALLINT NOT NULL,
COURSELETTER		CHAR NOT NULL,
PREREQDEPT			CHAR(4) NOT NULL,
PREREQNUM			SMALLINT NOT NULL,
PREREQCOURSELETTER	CHAR,
ISCOREQ				BOOLEAN,
FOREIGN KEY (COURSEID) REFERENCES COURSE (COURSEID)
)ENGINE = INNODB;

-- CREATE TABLE COREQUISITE(
-- COURSEDEPT			CHAR(4) NOT NULL,
-- COURSENUM			SMALLINT NOT NULL,
-- COURSELETTER		CHAR NOT NULL,
-- COREQDEPT			CHAR(4) NOT NULL,
-- COREQNUM			SMALLINT NOT NULL,
-- COREQCOURSELETTER	CHAR,
-- FOREIGN KEY (COURSEDEPT) REFERENCES COURSE (DEPTCODE),
-- FOREIGN KEY (COURSENUM) REFERENCES COURSE (COURSENUM),
-- FOREIGN KEY (COURSELETTER) REFERENCES COURSE (COURSELETTER)
-- );

#SECONDARY INDEX FOR COURSE SINCE THE PRIMARY INDEX IS THE INNODB OR COURSEID (CLUSTERED)
CREATE INDEX COURSEHEADER ON COURSE (DEPTCODE, COURSENUM, COURSELETTER);

SHOW FULL COLUMNS FROM COURSEPREREQ;
