version: '1'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    build: ./database
    ports:
      - "1434:1434"
