#CPSC 362 PROJECT
DROP DATABASE IF EXISTS COURSECATALOG;
CREATE DATABASE COURSECATALOG;

USE COURSECATALOG;

-- CREATE TABLE IF NOT EXISTS COURSE( 
-- 	DEPTCODE			CHAR(4) NOT NULL,
-- 	COURSENUM			SMALLINT NOT NULL,
-- 	COURSELETTER		CHAR,
-- 	COURSENAME			VARCHAR(100) NOT NULL,
-- 	COURSEDESCRIPTION	VARCHAR(300),
-- 	CREDITS				TINYINT NOT NULL,
-- 	GRADCREDIT			BOOL,
-- 	MAJMINREQ			BOOL,
-- 	PRIMARY KEY (DEPTCODE, COURSENUM, COURSELETTER)
-- 	#OLD PK IS DEPTCODE, COURSENUM, COURSELETTER
-- )ENGINE = INNODB;

-- yamato 2.23
CREATE TABLE IF NOT EXISTS COURSE( 
	DEPTCODE			CHAR(4) NOT NULL,
	COURSENUM			SMALLINT NOT NULL,
	COURSELETTER		CHAR,
	COURSENAME			VARCHAR(100) NOT NULL,
	COURSEDESCRIPTION	VARCHAR(300),
	CREDITS				TINYINT NOT NULL,
	GRADCREDIT			BOOL,
	MAJMINREQ			BOOL,

	PRIMARY KEY (DEPTCODE, COURSENUM, COURSELETTER)
	#OLD PK IS DEPTCODE, COURSENUM, COURSELETTER
)ENGINE = INNODB;

-- CREATE TABLE IF NOT EXISTS COURSEPREREQ(
-- COURSEDEPT			CHAR(4) NOT NULL,
-- COURSENUM			SMALLINT NOT NULL,
-- COURSELETTER		CHAR NOT NULL,
-- PREREQDEPT			CHAR(4) NOT NULL,
-- PREREQNUM			SMALLINT NOT NULL,
-- PREREQCOURSELETTER	CHAR,
-- ISCOREQ				BOOLEAN,
-- CONSTRAINT FKCoursePreReq
-- 	FOREIGN KEY (COURSEDEPT, COURSENUM, COURSELETTER) REFERENCES COURSE (DEPTCODE, COURSENUM, COURSELETTER)
-- )ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS COURSEREQ(
	DEPTCODE			CHAR(4) NOT NULL,
	COURSENUM			SMALLINT NOT NULL,
	COURSELETTER		CHAR,
	PREREQDEPT			CHAR(4) NOT NULL,
	PREREQNUM			SMALLINT NOT NULL,
	PREREQCOURSELETTER  CHAR,
	ISCOREQ				BOOLEAN,
	PRIMARY KEY (DEPTCODE, COURSENUM, COURSELETTER, PREREQDEPT, PREREQNUM, PREREQCOURSELETTER),
	CONSTRAINT FKCoursePreReq
		FOREIGN KEY (DEPTCODE, COURSENUM, COURSELETTER) REFERENCES COURSE (DEPTCODE, COURSENUM, COURSELETTER)
);

-- CREATE TABLE COREQUISITE(
-- COURSEDEPT			CHAR(4) NOT NULL,
-- COURSENUM			SMALLINT NOT NULL,
-- COURSELETTER		CHAR NOT NULL,
-- COREQDEPT			CHAR(4) NOT NULL,
-- COREQNUM			SMALLINT NOT NULL,
-- COREQCOURSELETTER	CHAR,
-- FOREIGN KEY (COURSEDEPT) REFERENCES COURSE (DEPTCODE),
-- FOREIGN KEY (COURSENUM) REFERENCES COURSE (COURSENUM),
-- FOREIGN KEY (COURSELETTER) REFERENCES COURSE (COURSELETTER)
-- );

#SECONDARY INDEX FOR COURSE SINCE THE PRIMARY INDEX IS THE INNODB OR COURSEID (CLUSTERED)
CREATE INDEX COURSEHEADER ON COURSE (DEPTCODE, COURSENUM, COURSELETTER);

SHOW FULL COLUMNS FROM COURSEPREREQ;
